# Generated by Django 6.1 on 2026-09-01 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadcoordinador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.area'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='estado_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.estadoactividad'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estado_participacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.estadoparticipacion'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.tipoactividad'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.ubicacion'),
        ),
    ]
