# Generated by Django 6.1.1 on 2026-09-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_tipo_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='area',
            field=models.CharField(choices=[('asuncion', 'Asunción'), ('central', 'Central'), ('interior', 'Interior'), ('virtual', 'Virtual'), ('otra', 'Otra')], default='asuncion', max_length=20, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Ubicación'),
        ),
    ]
